### PR TITLE
Make assertions work on macOS

### LINKED ISSUE #6026: [BUG]: use of undeclared identifier '__assert_fail'
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Compile-time Error

### Component

General CCCL

### Describe the bug

```c++
/Users/jfaibussowit/.cache/CPM/cccl/380ba9c2e33ce3c9da22c2bbda8451b95e57c2cf/lib/cmake/libcudacxx/../../../libcudacxx/include/cuda/std/__memory/construct_at.h:193:3: error: use of undeclared identifier '__assert_fail'
  193 |   _CCCL_ASSERT(__loc != nullptr, "null pointer given to destroy_at");
      |   ^
/Users/jfaibussowit/.cache/CPM/cccl/380ba9c2e33ce3c9da22c2bbda8451b95e57c2cf/lib/cmake/libcudacxx/../../../libcudacxx/include/cuda/std/__cccl/assert.h:147:45: note: expanded from macro '_CCCL_ASSERT'
  147 | #  define _CCCL_ASSERT(expression, message) _CCCL_ASSERT_HOST(expression, message)
      |                                             ^
/Users/jfaibussowit/.cache/CPM/cccl/380ba9c2e33ce3c9da22c2bbda8451b95e57c2cf/lib/cmake/libcudacxx/../../../libcudacxx/include/cuda/std/__cccl/assert.h:115:50: note: expanded from macro '_CCCL_ASSERT_HOST'
  115 | #  define _CCCL_ASSERT_HOST(expression, message) _CCCL_ASSERT_IMPL_HOST(expression, message)
      |                                                  ^
/Users/jfaibussowit/.cache/CPM/cccl/380ba9c2e33ce3c9da22c2bbda8451b95e57c2cf/lib/cmake/libcudacxx/../../../libcudacxx/include/cuda/std/__cccl/assert.h:86:18: note: expanded from macro '_CCCL_ASSERT_IMPL_HOST'
   86 |     ? (void) 0 : __assert_fail(message, __FILE__, __LINE__, __func__)
```

### How to Reproduce

Compile CCCL on macOS with Apple clang.
```sh
$ clang --version
Apple clang version 17.0.0 (clang-1700.3.19.1)
Target: arm64-apple-darwin24.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

### Expected behavior

No compile error

### Reproduction link

_No response_

### Operating System

Darwin jfaibussowit-mlt 24.6.0 Darwin Kernel Version 24.6.0: Mon Aug 11 21:16:34 PDT 2025; root:xnu-11417.140.69.701.11~1/RELEASE_ARM64_T6020 arm64

### nvidia-smi output

_No response_

### NVCC version

_No response_

### PR DESCRIPTION
**Pull request by miscco**
Some projects that rely on us e.g [Legate](https://github.com/nv-legate/legate) support [macOS](https://nv-legate.github.io/legate/installation.html#support-matrix)), so lets be nice and at least unblock them

Fixes #6026

### CODE REVIEW

File: libcudacxx/include/cuda/std/__cccl/os.h [hunk 1]
```diff
@@ -43,6 +43,12 @@
 #  define _CCCL_OS_QNX_() 0
 #endif
 
+#if defined(__APPLE__) || defined(__APPLE_CC__)
+#  define _CCCL_OS_APPLE_() 1
```
Comment (davebayer) [inline libcudacxx/include/cuda/std/__cccl/os.h:47]: Could you use this macro in thread backend detection instead of `defined(__APPLE__)`?

**Review by bernhardmgruber — APPROVED** [review]
