### PR TITLE
Ensure that `cuda::std::pair` is potentially trivially copyable

### LINKED ISSUE #1246: [BUG]: thrust::pair is not trivially copyable in CCCL branch/2.3.x
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Compile-time Error

### Component

Thrust

### Describe the bug

The `thrust::pair` class was trivially copyable in CCCL 2.2.0 but is not trivially copyable in `branch/2.3.x`. I suspect #262 is the PR that introduced this change (bug?).

This leads to compilation failures in RAPIDS cuDF because RMM requires `rmm::device_uvector` to use trivially copyable types. For example: https://github.com/rapidsai/cudf/actions/runs/7403019153/job/20142041800?pr=14704#step:8:1714
```
/home/coder/.conda/envs/rapids/include/rmm/device_uvector.hpp(78): error: static assertion failed with "device_uvector only supports types that are trivially copyable."
          detected during instantiation of class "rmm::device_uvector<T> [with T=cuda::std::__4::pair<std::size_t, std::size_t>]" 
/home/coder/cudf/cpp/src/copying/contiguous_split.cu(1412): here
```

### How to Reproduce

Switch between CCCL 2.2.0 and trunk. 2.2.0 passes, but trunk fails.
https://godbolt.org/z/oeEKa5577

Also see https://github.com/rapidsai/cudf/pull/14704

### Expected behavior

`thrust::pair` behavior should not change (it should be trivially copyable in CCCL trunk).

### Reproduction link

https://godbolt.org/z/oeEKa5577

### Operating System

_No response_

### nvidia-smi output

_No response_

### NVCC version

_No response_

### PR DESCRIPTION
**Pull request by miscco**
trivially copyable is a requirement for memcpy. We want to ensure that our pair implementation satisfies that whenever possible.

This is especially important for thrust::pair as that is used in rmm extensively.

Fixes #1246

### CODE REVIEW

**Comment by miscco** [comment]
I am currently investigating why gcc-12 segfaults. I believe this is because we now have a base class which should not have any effect but yeah

File: thrust/thrust/system/detail/sequential/partition.h [hunk 1]
```diff
@@ -173,6 +173,11 @@ _CCCL_HOST_DEVICE
                                    ForwardIterator last,
                                    Predicate pred)
 {
+  if (first == last)
+  {
+    return first;
+  }
```
Comment (gevtushenko) [inline thrust/thrust/system/detail/sequential/partition.h:179]: @miscco the seg fault in CUB tests happened in sequential (host-side) thrust sort. It seems to be GCC 12 miscompilation, since it only happens in release build when using `thrust::stable_sort` with empty `thrust::host_vector<bool>`. In this case, `stable_partition` is used, which constructs temporary array (no allocation). The seg fault happens when `logical_not` is called on an element of that temporary storage, which shouldn't happen, since it's only called inside the loop. 

I'll try to take a closer look if the changes you've made to pair affect temporary array or it's a bug on GCC end, but for now this fix should unblock you.

Comment (miscco) [reply thrust/thrust/system/detail/sequential/partition.h:179]: thats an awesome find thanks a lot

File: libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h [hunk 2]
```diff
@@ -69,707 +70,704 @@
...
+struct __pair_constraints
+{
+  static constexpr bool __implicit_default_constructible =
+    __is_implicitly_default_constructible<_T1>::value && __is_implicitly_default_constructible<_T2>::value;
+
+  static constexpr bool __explicit_default_constructible =
+    !__implicit_default_constructible && _LIBCUDACXX_TRAIT(is_default_constructible, _T1)
+    && _LIBCUDACXX_TRAIT(is_default_constructible, _T2);
+
+  static constexpr bool __implicit_copy_constructible_from_T =
```
Comment (griwes) [inline libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h:90]: So at first (just reading the traits) I thought that these 4 should have the `_from_T` suffix removed from their names, but seeing how they are used, I'd suggest something like `__implicit_constructible_from_element_copies` and so on; it might be longer, but since there's no `T` in scope here, even logically, I don't think the current names make much sense. (`_from_Ts` maybe, but I think that's still muddled in its meaning.)

File: libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h [hunk 3]
```diff
@@ -69,707 +70,704 @@
...
+
+  static constexpr bool __explicit_copy_constructible_from_T =
+    _LIBCUDACXX_TRAIT(is_copy_constructible, _T1) && _LIBCUDACXX_TRAIT(is_copy_constructible, _T2)
+    && (!_LIBCUDACXX_TRAIT(is_convertible, __make_const_lvalue_ref<_T1>, _T1)
+        || !_LIBCUDACXX_TRAIT(is_convertible, __make_const_lvalue_ref<_T2>, _T2));
+
+  static constexpr bool __implicit_move_constructible_from_T =
+    _LIBCUDACXX_TRAIT(is_move_constructible, _T1) && _LIBCUDACXX_TRAIT(is_move_constructible, _T2)
+    && _LIBCUDACXX_TRAIT(is_convertible, __make_const_lvalue_ref<_T1>, _T1)
+    && _LIBCUDACXX_TRAIT(is_convertible, __make_const_lvalue_ref<_T2>, _T2);
```
Comment (griwes) [inline libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h:103]: `__make_const_lvalue_ref` looks very wrong here, since we are checking moves. This should probably just use `_T1, _T1` like in the explicit version of this below, right?

File: libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h [hunk 4]
```diff
@@ -69,707 +70,704 @@
...
-#endif // defined(__cuda_std__) && !defined(__CUDACC_RTC__)
+template <class _T1, class _T2>
+struct __must_synthesize_assignment
+    : integral_constant<bool,
+                        (_LIBCUDACXX_TRAIT(is_copy_assignable, _T1) && _LIBCUDACXX_TRAIT(is_copy_assignable, _T2)
+                         && !(_LIBCUDACXX_TRAIT(is_copy_assignable, _TestSynthesizeAssignment<_T1>)
+                              && _LIBCUDACXX_TRAIT(is_copy_assignable, _TestSynthesizeAssignment<_T2>)))
+                          || (_LIBCUDACXX_TRAIT(is_copy_assignable, _T1) && _LIBCUDACXX_TRAIT(is_copy_assignable, _T2)
+                              && !(_LIBCUDACXX_TRAIT(is_copy_assignable, _TestSynthesizeAssignment<_T1>)
+                                   && _LIBCUDACXX_TRAIT(is_copy_assignable, _TestSynthesizeAssignment<_T2>)))>
```
Comment (griwes) [inline libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h:146]: Is the second part here supposed to check move and not copy constructible? Because unless I'm missing something, both arguments to the logical sum look identical to me.

File: libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h [hunk 5]
```diff
@@ -69,707 +70,704 @@
...
+{};
+
+// base class to ensure `is_trivially_copyable` when possible
+template <class _T1, class _T2, bool = __must_synthesize_assignment<_T1, _T2>::value>
+struct __pair_base
+{
+  _T1 first;
+  _T2 second;
+
+  template <class _Constraints                                                 = __pair_constraints<_T1, _T2>,
```
Comment (griwes) [inline libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h:156]: Side note: I *hate* how this gets formatted.

File: libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h [hunk 6]
```diff
@@ -69,707 +70,704 @@
...
+  {}
+
+  constexpr __pair_base(const __pair_base&) = default;
+  constexpr __pair_base(__pair_base&&)      = default;
+
+  _LIBCUDACXX_INLINE_VISIBILITY _LIBCUDACXX_CONSTEXPR_AFTER_CXX11 __pair_base& operator=(
+    __conditional_t<_LIBCUDACXX_TRAIT(is_copy_assignable, _T1) && _LIBCUDACXX_TRAIT(is_copy_assignable, _T2),
+                    __pair_base,
+                    __nat> const& __p) noexcept(_LIBCUDACXX_TRAIT(is_nothrow_move_assignable, _T1)
+                                                && _LIBCUDACXX_TRAIT(is_nothrow_move_assignable, _T2))
```
Comment (griwes) [inline libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h:223]: `s/move/copy/`

File: libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h [hunk 7]
```diff
@@ -69,707 +70,704 @@
...
+  }
+
+  _LIBCUDACXX_INLINE_VISIBILITY _LIBCUDACXX_CONSTEXPR_AFTER_CXX11 __pair_base& operator=(
+    __conditional_t<_LIBCUDACXX_TRAIT(is_move_assignable, _T1) && _LIBCUDACXX_TRAIT(is_move_assignable, _T2),
+                    __pair_base,
+                    __nat>&& __p) noexcept(_LIBCUDACXX_TRAIT(is_nothrow_move_assignable, _T1)
+                                           && _LIBCUDACXX_TRAIT(is_nothrow_move_assignable, _T2))
+  {
+    first  = _CUDA_VSTD::forward<_T1>(__p.first);
+    second = _CUDA_VSTD::forward<_T2>(__p.second);
```
Comment (griwes) [inline libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h:237]: This warrants a comment, because at first I couldn't figure out what's going on here, until I exclaimed "oh, references!".

File: libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h [hunk 8]
```diff
@@ -69,707 +70,704 @@
...
+    _LIBCUDACXX_TRAIT(is_nothrow_copy_constructible, _T1) && _LIBCUDACXX_TRAIT(is_nothrow_copy_constructible, _T2))
+      : __base(__t1, __t2)
+  {}
+
+  template <class _Constraints                                                     = __pair_constraints<_T1, _T2>,
+            __enable_if_t<_Constraints::__implicit_copy_constructible_from_T, int> = 0>
+  _LIBCUDACXX_INLINE_VISIBILITY constexpr pair(const _T1& __t1, const _T2& __t2) noexcept(
+    _LIBCUDACXX_TRAIT(is_nothrow_copy_constructible, _T1) && _LIBCUDACXX_TRAIT(is_nothrow_copy_constructible, _T2))
+      : __base(__t1, __t2)
+  {}
```
Comment (griwes) [inline libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h:294]: In other places the implicit version is at the top and the explicit one is at the bottom of the pair; can you harmonize this throughout this file?

File: libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h [hunk 9]
```diff
@@ -69,707 +70,704 @@
...
+      : __base(_CUDA_VSTD::forward<_U1>(__u1), _CUDA_VSTD::forward<_U2>(__u2))
+  {}
+
+  template <class... _Args1, class... _Args2>
+  _LIBCUDACXX_INLINE_VISIBILITY _LIBCUDACXX_CONSTEXPR_AFTER_CXX17
+  pair(piecewise_construct_t __pc, tuple<_Args1...> __first_args, tuple<_Args2...> __second_args) noexcept(
+    (is_nothrow_constructible<first_type, _Args1...>::value && is_nothrow_constructible<second_type, _Args2...>::value))
+      : __base(__pc,
+               __first_args,
+               __second_args,
```
Comment (griwes) [inline libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h:320]: These should be moved here, no?

File: libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h [hunk 10]
```diff
@@ -69,707 +70,704 @@
...
+               __make_tuple_indices_t<sizeof...(_Args1)>(),
+               __make_tuple_indices_t<sizeof...(_Args2)>())
+  {}
+
+  // copy constructors
```
Comment (griwes) [inline libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h:325]:
```suggestion
  // copy and move constructors
```

File: libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h [hunk 11]
```diff
@@ -69,707 +70,704 @@
...
+      : __base(__p.first, __p.second)
+  {}
+
+  // move constructors
+  template <class _U1          = _T1,
+            class _U2          = _T2,
+            class _Constraints = typename __pair_constraints<_T1, _T2>::template __constructible<_U1, _U2>,
+            __enable_if_t<_Constraints::__explicit_constructible, int> = 0>
+  _LIBCUDACXX_INLINE_VISIBILITY explicit _LIBCUDACXX_CONSTEXPR_AFTER_CXX11 pair(pair<_U1, _U2>&& __p) noexcept(
+    _LIBCUDACXX_TRAIT(is_nothrow_constructible, _T1, _U1) && _LIBCUDACXX_TRAIT(is_nothrow_constructible, _T2, _U2))
```
Comment (griwes) [inline libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h:355]: In this constructor and related, shouldn't the test be for constructibility from `_U1&&` and `_U2&&`, not just `_U1` and `_U2`? You do add the `&&` in the test for assignment operators below, but not here, I don't see why there would be a difference, and the one on assignments feels more correct.

File: libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h [hunk 12]
```diff
@@ -69,707 +70,704 @@
...
-               is_assignable_v<const second_type&, _U2>) {
-        first = _CUDA_VSTD::forward<_U1>(__p.first);
-        second = _CUDA_VSTD::forward<_U2>(__p.second);
-        return *this;
-    }
-#endif // defined(__cuda_std__) && !defined(__CUDACC_RTC__)
+  _LIBCUDACXX_HIDE_FROM_ABI _LIBCUDACXX_INLINE_VISIBILITY constexpr const pair& operator=(pair const& __p) const
+    noexcept(_LIBCUDACXX_TRAIT(is_nothrow_copy_assignable, const _T1)
+             && _LIBCUDACXX_TRAIT(is_nothrow_copy_assignable, const _T2))
+    requires(is_copy_assignable_v<const first_type> && is_copy_assignable_v<const second_type>)
```
Comment (griwes) [inline libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h:465]: In this hunk, the previous code uses `{first,second}_type` consistently, but you're now using both `{first,second}_type` and `_T{1,2}` in all (I think?) signatures that include a concept check, please settle on one.

File: libcudacxx/test/support/archetypes.ipp [hunk 13]
```diff
@@ -24,6 +24,13 @@
 #define DEFINE_ASSIGN_CONSTEXPR
 #endif
 #endif
+#ifndef DEFINE_DEFAULT_CONSTEXPR
```
Comment (griwes) [inline libcudacxx/test/support/archetypes.ipp:27]: Ah yes, love it when a need comes to add another macro to this header. /s

**Review by griwes — CHANGES_REQUESTED** [review]

File: libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h [hunk 14]
```diff
@@ -69,707 +70,704 @@
...
-        return *this;
-    }
+// We need to ensure that a reference type, which would inhibit the implicit copy assignment still works
+template <class _T1, class _T2>
+struct __pair_base<_T1, _T2, true>
+{
+  _T1 first;
+  _T2 second;
+
+  template <class _Constraints                                                 = __pair_constraints<_T1, _T2>,
```
Comment (gevtushenko) [inline libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h:198]: question: symbols are quite different now:
```
_ZN4cuda3std3__44pairI1AS3_EC2IS3_S3_NS1_18__pair_constraintsIS3_S3_E15__constructibleIS3_S3_EETnNS1_9enable_ifIXsrT1_24__implicit_constructibleEiE4typeELi0EEEOT_OT0_
```
vs
```
_ZN4cuda3std3__44pairI1AS3_EC2IS3_S3_TnPNS1_9enable_ifIXsr10_CheckArgs17__enable_implicitIT_T0_EE5valueEvE4typeELPv0EEEOS7_OS8_
```
Do we need to bump ABI version?

File: libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h [hunk 15]
```diff
@@ -69,707 +70,704 @@
...
-    {
-        first = __p.first;
-        second = __p.second;
-        return *this;
-    }
+// We need to synthesize the copy / move assignment if it would be implicitly deleted as a member of a class
+// In that case _T1 would be copy assignable but _TestSynthesizeAssignment<_T1> would not
+// This happens e.g for reference types
+template <class _T1>
+struct _TestSynthesizeAssignment
```
[the remark this answers is not in the document]
Comment (gevtushenko) [reply libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h:133]: Not sure what's the convention in libcu++, in cub it's camel case for template parameters and snake case for everything else (in new style).

File: libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h (hunk 5 above)
Comment (gevtushenko) [reply libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h:156]: > but the alternative is worse

@miscco I'm not sure. I'd gladly avoid aligning by operators altogether.

File: libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h (hunk 15 above)
[the remark this answers is not in the document]
Comment (miscco) [reply libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h:133]: That is what I try to do too, but the issue is that libc++ has a totally different style of `everything snake case`

I want to be able to see whether something is a type or a function / variable but at the same time I dont want to rewrite the world

File: libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h (hunk 5 above)
Comment (miscco) [reply libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h:156]: The issue is that usually aligning template parameters is highly beneficial and improves readability a lot. 

Its only when you have larger defaults like here that it breaks down

File: libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h (hunk 2 above)
Comment (griwes) [reply libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h]: The thing I probably dislike the most about the current name is that it contains "copy_constructible". This has a meaning - this thing we are constructing is created using its copy constructor. But that's not what's happening here, hence my original suggestion.

File: libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h (hunk 14 above)
Comment (griwes) [reply libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h:188]: Yeah, I _think_ this is fine. Code that was compiled with the old version will have distinct mangled names from the new version, so they can easily coexist in the same program. As @miscco said, at worst this is a linker error forcing recompilation.

When we do a release, however, this should probably be spelled out as a change potentially requiring recompilation in the release notes.

File: libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h (hunk 2 above)
Comment (miscco) [reply libcudacxx/include/cuda/std/detail/libcxx/include/__utility/pair.h]: Oh yeah, we should just name that `__{implicit,explicit}_constructible_from_elements`

**Comment by miscco** [comment]
@griwes I have changed the name to `__{implicit,explicit}_constructible_from_elements` If there is nothing else we can merge this once you approve

**Review by griwes — APPROVED** [review]
