### PR TITLE
Fix `{host, device, managed}_mdspan`

### LINKED ISSUE #6076: [BUG]: `cuda::host_mdspan` and `cuda::device_mdspan` examples fail to compile
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Compile-time Error

### Component

libcu++

### Describe the bug

`cuda::host_mdspan` and `cuda::device_mdspan` Godbolt examples fail to compile due to missing deduction guides for these types. The `cuda::std::mdspan` deduction guides do not apply here, because these types don't use the `cuda::std::default_accessor`.

### How to Reproduce

See https://godbolt.org/z/fezxsbjaq

### Expected behavior

Should work.

### Reproduction link

https://godbolt.org/z/fezxsbjaq

### Operating System

_No response_

### nvidia-smi output

_No response_

### NVCC version

_No response_

### PR DESCRIPTION
**Pull request by miscco**
Our specialized `mdspan` implementations were slightly broken.

* the constraints on the constructors were wrong
* with them being alias templates, CTAD did not work

Fix this by properly implementing them as classes and also adding some proper testing

Fixes #6076

### CODE REVIEW

File: libcudacxx/include/cuda/__mdspan/host_device_accessor.h [hunk 1]
```diff
@@ -107,10 +109,17 @@ class __host_accessor : public _Accessor
 #if _CCCL_HAS_CTK()
     if constexpr (::cuda::std::contiguous_iterator<__data_handle_type>)
     {
-      ::cudaPointerAttributes __ptr_attrib{};
-      auto __p1 = ::cuda::std::to_address(__p);
-      _CCCL_ASSERT_CUDA_API(::cudaPointerGetAttributes, "cudaPointerGetAttributes failed", &__ptr_attrib, __p1);
-      return __ptr_attrib.hostPointer != nullptr || __ptr_attrib.type == ::cudaMemoryTypeUnregistered;
+      if (!cuda::std::__cccl_default_is_constant_evaluated())
```
Comment (miscco) [inline libcudacxx/include/cuda/__mdspan/host_device_accessor.h:116]: This makes it usable in a constant expression

File: libcudacxx/include/cuda/__mdspan/host_device_accessor.h [hunk 2]
```diff
@@ -132,10 +136,15 @@ class __host_accessor : public _Accessor
 
   _CCCL_TEMPLATE(class _Accessor2 = _Accessor)
   _CCCL_REQUIRES(::cuda::std::is_default_constructible_v<_Accessor2>)
-  _CCCL_API inline __host_accessor() noexcept(::cuda::std::is_nothrow_default_constructible_v<_Accessor2>)
+  _CCCL_API constexpr __host_accessor() noexcept(::cuda::std::is_nothrow_default_constructible_v<_Accessor2>)
```
Comment (miscco) [inline libcudacxx/include/cuda/__mdspan/host_device_accessor.h:142]: Missing constexpr

File: libcudacxx/include/cuda/__mdspan/host_device_accessor.h [hunk 3]
```diff
@@ -145,44 +154,59 @@ class __host_accessor : public _Accessor
   __host_accessor(const __device_accessor<_OtherAccessor>&) = delete;
 
   _CCCL_TEMPLATE(typename _OtherAccessor)
-  _CCCL_REQUIRES(
-    ::cuda::std::is_constructible_v<_OtherAccessor> _CCCL_AND(::cuda::std::is_convertible_v<_OtherAccessor, _Accessor>))
-  _CCCL_API constexpr __host_accessor(const __host_accessor<_OtherAccessor>& __acc) noexcept(noexcept(_Accessor{
-    ::cuda::std::declval<_OtherAccessor>()}))
+  _CCCL_REQUIRES(::cuda::std::is_constructible_v<_Accessor, const _OtherAccessor&> _CCCL_AND(
```
Comment (miscco) [inline libcudacxx/include/cuda/__mdspan/host_device_accessor.h:160]: Those constraints were wrong

File: libcudacxx/include/cuda/__mdspan/host_device_accessor.h [hunk 4]
```diff
@@ -145,44 +154,59 @@ class __host_accessor : public _Accessor
...
       : _Accessor{__acc}
   {}
 
   _CCCL_TEMPLATE(typename _OtherAccessor)
-  _CCCL_REQUIRES(
-    ::cuda::std::is_constructible_v<_OtherAccessor> _CCCL_AND(::cuda::std::is_convertible_v<_OtherAccessor, _Accessor>))
-  _CCCL_API constexpr __host_accessor(const __managed_accessor<_OtherAccessor>& __acc) noexcept(noexcept(_Accessor{
-    ::cuda::std::declval<_OtherAccessor>()}))
-      : _Accessor{__acc}
+  _CCCL_REQUIRES(::cuda::std::is_constructible_v<_Accessor, _OtherAccessor> _CCCL_AND(
```
Comment (miscco) [inline libcudacxx/include/cuda/__mdspan/host_device_accessor.h:176]: We should also cover move construction

File: libcudacxx/include/cuda/__mdspan/host_device_accessor.h [hunk 5]
```diff
@@ -145,44 +154,59 @@ class __host_accessor : public _Accessor
...
   {
-#if _CCCL_HOST_COMPILATION()
-    __check_host_pointer(__p);
-#else // ^^^ _CCCL_HOST_COMPILATION() ^^^ // vvv !_CCCL_HOST_COMPILATION() vvv
-    static_assert(false, "cuda::__host_accessor cannot be used in DEVICE code");
-#endif // !_CCCL_HOST_COMPILATION()
+    NV_IF_ELSE_TARGET(
+      NV_IS_DEVICE,
+      (_CCCL_ASSERT(false, "cuda::__host_accessor cannot be used in DEVICE code");),
+      (_CCCL_ASSERT(__is_host_accessible_pointer(__p), "cuda::__host_accessor data handle is not a HOST pointer");))
```
Comment (miscco) [inline libcudacxx/include/cuda/__mdspan/host_device_accessor.h:212]: We cannot make this a static_assert, nvcc barfs if this is solely included

File: libcudacxx/include/cuda/__mdspan/host_device_accessor.h
Comment (davebayer) [inline libcudacxx/include/cuda/__mdspan/host_device_accessor.h]:
```suggestion
  [[nodiscard]] _CCCL_HOST_API static constexpr bool
```
+ wrap by `#if !_CCCL_COMPILER(NVRTC)`

File: libcudacxx/include/cuda/__mdspan/host_device_accessor.h [hunk 6]
```diff
@@ -147,44 +157,59 @@ class __host_accessor : public _Accessor
...
   _CCCL_API constexpr reference access(data_handle_type __p, size_t __i) const noexcept(__is_access_noexcept)
   {
-#if _CCCL_HOST_COMPILATION()
-    __check_host_pointer(__p);
-#else // ^^^ _CCCL_HOST_COMPILATION() ^^^ // vvv !_CCCL_HOST_COMPILATION() vvv
-    static_assert(false, "cuda::__host_accessor cannot be used in DEVICE code");
-#endif // !_CCCL_HOST_COMPILATION()
+    NV_IF_ELSE_TARGET(
+      NV_IS_DEVICE,
+      (_CCCL_ASSERT(false, "cuda::__host_accessor cannot be used in DEVICE code");),
```
Comment (davebayer) [inline libcudacxx/include/cuda/__mdspan/host_device_accessor.h]: Shouldn't this be `_CCCL_VERIFY`?

File: libcudacxx/include/cuda/__mdspan/host_device_accessor.h [hunk 7]
```diff
@@ -28,11 +28,14 @@
 #include <cuda/std/__iterator/concepts.h>
 #include <cuda/std/__memory/pointer_traits.h>
 #include <cuda/std/__type_traits/always_false.h>
+#include <cuda/std/__type_traits/is_constructible.h>
 #include <cuda/std/__type_traits/is_convertible.h>
 #include <cuda/std/__type_traits/is_default_constructible.h>
+#include <cuda/std/__type_traits/is_nothrow_constructible.h>
 #include <cuda/std/__type_traits/is_nothrow_copy_constructible.h>
 #include <cuda/std/__type_traits/is_nothrow_default_constructible.h>
```
Comment (davebayer) [inline libcudacxx/include/cuda/__mdspan/host_device_accessor.h:37]:
```suggestion
#include <cuda/std/__type_traits/is_nothrow_default_constructible.h>
#include <cuda/std/__type_traits/is_constant_evaluated.h>
```

File: libcudacxx/include/cuda/__mdspan/host_device_mdspan.h [hunk 8]
```diff
@@ -32,19 +42,184 @@ template <typename _ElementType,
...
+
+  _CCCL_API friend constexpr void swap(host_mdspan& __x, host_mdspan& __y) noexcept
+  {
+    swap(static_cast<__base&>(__x), static_cast<__base&>(__y));
+  }
+};
+
+_CCCL_TEMPLATE(class _ElementType, class... _OtherIndexTypes)
+_CCCL_REQUIRES((sizeof...(_OtherIndexTypes) > 0)
+                 _CCCL_AND(::cuda::std::is_convertible_v<_OtherIndexTypes, size_t>&&... && true))
```
Comment (davebayer) [inline libcudacxx/include/cuda/__mdspan/host_device_mdspan.h]:
```suggestion
                 _CCCL_AND(::cuda::std::is_convertible_v<_OtherIndexTypes, size_t> && ...))
```
And wouldn't here be a problem with fold expression in template header?

File: libcudacxx/include/cuda/__mdspan/restrict_mdspan.h [hunk 9]
```diff
@@ -32,7 +42,63 @@ template <typename _ElementType,
...
+_CCCL_HOST_DEVICE restrict_mdspan(_ElementType*, const ::cuda::std::extents<_OtherIndexType, _ExtentsPack...>&)
+  -> restrict_mdspan<_ElementType, ::cuda::std::extents<_OtherIndexType, _ExtentsPack...>>;
+
+template <class _ElementType, class _MappingType>
+_CCCL_HOST_DEVICE restrict_mdspan(_ElementType*, const _MappingType&)
+  -> restrict_mdspan<_ElementType, typename _MappingType::extents_type, typename _MappingType::layout_type>;
+
+template <class _MappingType, class _AccessorType>
+_CCCL_HOST_DEVICE
+restrict_mdspan(const typename _AccessorType::data_handle_type, const _MappingType&, const _AccessorType&)
```
Comment (fbusato) [inline libcudacxx/include/cuda/__mdspan/restrict_mdspan.h:97]: is `const typename` intended?

File: libcudacxx/include/cuda/__mdspan/host_device_accessor.h [hunk 10]
```diff
@@ -108,11 +111,18 @@ class __host_accessor : public _Accessor
...
+      if (!cuda::std::__cccl_default_is_constant_evaluated())
+      {
+        auto __p1 = ::cuda::std::to_address(__p);
+        ::CUmemorytype __type{};
+        const auto __status =
+          ::cuda::__driver::__pointerGetAttributeNoThrow<::CU_POINTER_ATTRIBUTE_MEMORY_TYPE>(__type, __p1);
+        return (__status != ::cudaSuccess) || __type == ::CU_MEMORYTYPE_HOST;
+      }
+      else
+      {
```
Comment (fbusato) [inline libcudacxx/include/cuda/__mdspan/host_device_accessor.h]: what about using just `return true;` at the end of the function, without `else`?

File: libcudacxx/include/cuda/__mdspan/host_device_accessor.h (hunk 3 above)
Comment (fbusato) [reply libcudacxx/include/cuda/__mdspan/host_device_accessor.h:160]: I guess because I used the old implementation as reference

File: libcudacxx/include/cuda/__mdspan/host_device_accessor.h [hunk 11]
```diff
@@ -108,11 +111,18 @@ class __host_accessor : public _Accessor
 #if _CCCL_HAS_CTK()
     if constexpr (::cuda::std::contiguous_iterator<__data_handle_type>)
     {
```
Comment (fbusato) [inline libcudacxx/include/cuda/__mdspan/host_device_accessor.h:115]: reminder for myself. I want to move all these functionalities in a dedicated header to allow reuse

File: libcudacxx/test/libcudacxx/cuda/containers/views/mdspan/device_mdspan/assign.pass.cpp [hunk 12]
```diff
@@ -0,0 +1,157 @@
+//===----------------------------------------------------------------------===//
```
Comment (fbusato) [inline libcudacxx/test/libcudacxx/cuda/containers/views/mdspan/device_mdspan/assign.pass.cpp:1]: so now we have the same tests for `cuda::std::mdspan` and `cuda::*_mdspan`, is it correct?

**Review by fbusato — APPROVED** [review]

File: libcudacxx/include/cuda/__mdspan/host_device_accessor.h (hunk 6 above)
Comment (fbusato) [reply libcudacxx/include/cuda/__mdspan/host_device_accessor.h]: that's a good idea. My initial solution was to use the `static_assert` in a template function, e.g. `template<int X = 0>` + `static_assert(X != X)` to delay the instantiation. Maybe `nvcc` also complains in this case

File: libcudacxx/include/cuda/__mdspan/host_device_accessor.h
Comment (fbusato) [reply libcudacxx/include/cuda/__mdspan/host_device_accessor.h]: what about just `HOST_COMPILATION` (within the function)?

File: libcudacxx/include/cuda/__mdspan/host_device_accessor.h (hunk 6 above)
Comment (miscco) [reply libcudacxx/include/cuda/__mdspan/host_device_accessor.h]: yeah i tried those as well but it always complained even with a `static_assert(___always_false<>)`

Comment (davebayer) [reply libcudacxx/include/cuda/__mdspan/host_device_accessor.h]: Yeah, I tried it as well in the past, but it seems that the method gets instantiated everytime :(

File: libcudacxx/include/cuda/__mdspan/restrict_mdspan.h (hunk 9 above)
Comment (miscco) [reply libcudacxx/include/cuda/__mdspan/restrict_mdspan.h:97]: I love my const correctness

File: libcudacxx/test/libcudacxx/cuda/containers/views/mdspan/device_mdspan/assign.pass.cpp (hunk 12 above)
Comment (miscco) [reply libcudacxx/test/libcudacxx/cuda/containers/views/mdspan/device_mdspan/assign.pass.cpp:1]: Yes

File: libcudacxx/include/cuda/__mdspan/host_device_accessor.h
Comment (miscco) [reply libcudacxx/include/cuda/__mdspan/host_device_accessor.h]: I believe this is not correct, for a host device accessible memory location we want to be able to ask this question

Comment (davebayer) [reply libcudacxx/include/cuda/__mdspan/host_device_accessor.h]: But this function works in host code only. So there is no reason to have this function in device code, too, it should fail to compile anyway, because driver API is not available in device code.

Note that we call this function only in `NV_IF_ELSE_TARGET` for host.
