### PR TITLE
Fixes for thrust::shuffle

### LINKED ISSUE #7159: [BUG]: Fix randomness in thrust::shuffle_iterator
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Runtime Error

### Component

Thrust

### Describe the bug

The fix landed in libcudacxx (#7130), which is copied/pasted from Thrust. We need to backport the fix to Thrust, and then back port to v3.2.x.

### How to Reproduce

n/a

### Expected behavior

n/a

### Reproduction link

_No response_

### Operating System

_No response_

### nvidia-smi output

_No response_

### NVCC version

_No response_

### PR DESCRIPTION
**Pull request by RAMitchell**
Fix #7159

Another fix is that bit_with(256)=9. We only need 8, so the calculation becomes total_bits = bit_width(n - 1). The previous implementation is wasting compute for powers of two.

There are some errors in the thrust shuffle randomness tests.
- Chi squared tests being applied to continous quantities, which are also not independant
- Large numbers of chi squared tests being run in a loop. The significance is incorrect when you run multiple tests.

### CODE REVIEW

File: libcudacxx/include/cuda/__random/feistel_bijection.h [hunk 1]
```diff
@@ -51,7 +51,10 @@ class __feistel_bijection
   template <class _RNG>
   _CCCL_API __feistel_bijection(uint64_t __num_elements, _RNG&& __gen)
   {
-    const uint64_t __total_bits = static_cast<uint64_t>(::cuda::std::max(8, ::cuda::std::bit_width(__num_elements)));
+    // Calculate number of bits needed to represent num_elements - 1
+    // Prevent zero
+    const uint64_t __max_index  = ::cuda::std::max(static_cast<uint64_t>(1), __num_elements) - 1;
```
Comment (miscco) [inline libcudacxx/include/cuda/__random/feistel_bijection.h:56]: Technically this would regress the case of 0 elements

Comment (RAMitchell) [reply libcudacxx/include/cuda/__random/feistel_bijection.h:56]: Doesn't `__num_elements=0` result in `__total_bits=8`? I don't see the mistake. There is also a test for this case which results in size 256.

Comment (miscco) [reply libcudacxx/include/cuda/__random/feistel_bijection.h:56]: oh yeah you are correct

File: thrust/thrust/detail/random_bijection.h [hunk 2]
```diff
@@ -34,25 +35,22 @@ namespace detail
 //! \brief A Feistel cipher for operating on power of two sized problems
 class feistel_bijection
```
Comment (miscco) [inline thrust/thrust/detail/random_bijection.h:36]: Just for me, why cannot we just do
```suggestion
using feistel_bijection = ::cuda::__feistel_bijection;
```

Comment (RAMitchell) [reply thrust/thrust/detail/random_bijection.h:36]: `::cuda::__feistel_bijection` uses a URBG inside and when we use the thrust one it fails to compile. As you mentioned one option would be to allow uniform_int_distribution to accept an incorrect URBG. Otherwise we have to duplicate.

**Comment by leofang** [comment]
Much appreciated, @RAMitchell 🙏
