### PR TITLE
Ensure that {cr}begin works with types that pull in namespace std via ADL

### LINKED ISSUE #1679: [BUG]: thrust iterators are not compatible with absl container algorithms.
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Compile-time Error

### Component

Not sure

### Describe the bug

Container algorithms from ABSL fail to compile when used w/ thrust iterators. Note that it's completely host-side C++ code, not CUDA.

Note that it's not clear what's at fault here: absl, thrust, libcu++ or my expectations that it should all work.

For what it's worth, the code used to work with an ancient version of thrust (https://github.com/NVIDIA/thrust/tree/f5ea60fd3aa3828c0eb8991a54acdfbed6707bd7)

### How to Reproduce

https://godbolt.org/z/a4v4hecsP

### Expected behavior

absl algorithms should work with thrust iterators.

### Reproduction link

https://godbolt.org/z/a4v4hecsP

### Operating System

n/a

### nvidia-smi output

n/a

### NVCC version

It's a host-side compilation issue. The failure happens with both clang and gcc.

### PR DESCRIPTION
**Pull request by miscco**
Those types must be host only so we can safely SFINAE away our own free functions that would be ambiguous

Fixes #1679

### CODE REVIEW

**Comment by miscco** [comment]
@Artem-B could you verify that this fixes your issues?

**Comment by miscco** [comment]
The obvious wrinkle here is that those types wont find `cuda::std::begin` but AFAIK there is nothing we can do there and it is better than always breaking compilation

**Comment by miscco** [comment]
I also added a workaround for `swap` which suffers from the same issue

**Comment by Artem-B** [comment]
The patch appears to work, but I can only test it on reduced reproducers, and not on the rest of our code.

Would it be possible to back-port the patch to `v2.3.2` so I could apply it to CCCL sources we're currently using? It appears that a lot of files moved around and reformatted lately and my attempts to merge this PR diff fail, no matter what I do.

File: libcudacxx/include/cuda/std/__iterator/access.h [hunk 1]
```diff
@@ -21,47 +21,101 @@
...
+template <class _Tp, size_t _Np>
+_LIBCUDACXX_INLINE_VISIBILITY auto __begin(_Tp (&__array)[_Np]) -> decltype(begin(__array));
+template <class _Cont>
+_LIBCUDACXX_INLINE_VISIBILITY auto __begin(_Cont& __c) -> decltype(begin(__c));
+template <class _Cont>
+_LIBCUDACXX_INLINE_VISIBILITY auto __begin(const _Cont& __c) -> decltype(begin(__c));
+_LIBCUDACXX_INLINE_VISIBILITY auto __begin(...) -> __not_ambiguous;
+template <class _Cont>
+struct __begin_not_ambiguous
+    : is_same<decltype(__detect_ambiguous_access::__begin(_CUDA_VSTD::declval<_Cont>())), __not_ambiguous>
```
Comment (bernhardmgruber) [inline libcudacxx/include/cuda/std/__iterator/access.h:48]: Suggestion: This meta function does not check whether `__begin(Cont)` is ambigous. It checks whether there is a reachable overload. So I would name it differently, like: `has___begin_overload_for`.

Then the constraint later would read:
```c++
template <class _Tp, size_t _Np>
__enable_if_t<!__detect_ambiguous_access::has___begin_overload_for<_Tp (&)[_Np]>::value, _Tp*>
```
Which is a tiny improvement in readability.

File: libcudacxx/include/cuda/std/__type_traits/is_swappable.h [hunk 2]
```diff
@@ -36,22 +37,74 @@
...
+              __no_swap_found>
+{};
+template <class _Tp, size_t _Np>
+struct __has_no_adl_swap_array
+    : is_same<
+        decltype(__detect_adl_swap::__swap(_CUDA_VSTD::declval<_Tp (&)[_Np]>(), _CUDA_VSTD::declval<_Tp (&)[_Np]>())),
+        __no_swap_found>
+{};
+
+// We should only define swap if there is no adl found function or it is a hidden friend
```
Comment (bernhardmgruber) [inline libcudacxx/include/cuda/std/__type_traits/is_swappable.h:83]: Nit: You spelled ADL in ALLCAPS in other places.
```suggestion
// We should only define swap if there is no ADL-found function or it is a hidden friend
```

File: libcudacxx/include/cuda/std/__iterator/access.h
Comment (bernhardmgruber) [inline libcudacxx/include/cuda/std/__iterator/access.h:1]: Question: Do I understand correctly that special handling for `cbegin` and `cend` is not necessary, because they already SFINAE out when no corresponding `begin` or `end` is available in `::cuda::std`?

Comment (miscco) [reply libcudacxx/include/cuda/std/__iterator/access.h:1]: > Question: Do I understand correctly that special handling for `cbegin` and `cend` is not necessary, because they already SFINAE out when no corresponding `begin` or `end` is available in `::cuda::std`?

That is correct, they explicitly use `_CUDA_VSTD::{begin, end}`

File: libcudacxx/include/cuda/std/__iterator/access.h (hunk 1 above)
Comment (miscco) [reply libcudacxx/include/cuda/std/__iterator/access.h:48]: :+1: I went with `__has_no_adl_meow`

**Comment by Artem-B** [comment]
> @Artem-B I have pushed backported fixes here https://github.com/miscco/cccl/tree/backport_adl_fixes

Thank you. It does fix the issues I had and so far I do not see any new failures. There are a handful of cases where we ended up generating some local memory loads/stores, but that will need a closer look to see if I need to bump compiler thresholds, or if cccl may need an explicit loop unroll or inline somewhere.

**Comment by Artem-B** [comment]
It may have broken one test: 

```
third_party/gpus/cccl/libcudacxx/test/libcudacxx/std/utilities/meta/meta.unary/meta.unary.prop/is_swappable.pass.cpp:99:23: error: static assertion failed due to requirement '!cuda::std::is_swappable<MyNS2::AmbiguousSwap>::value':
   99 |         static_assert(!cuda::std::is_swappable<MyNS2::AmbiguousSwap>::value, "");
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated when compiling for sm_60.
```

**Comment by miscco** [comment]
> It may have broken one test:
> 
> ```
> third_party/gpus/cccl/libcudacxx/test/libcudacxx/std/utilities/meta/meta.unary/meta.unary.prop/is_swappable.pass.cpp:99:23: error: static assertion failed due to requirement '!cuda::std::is_swappable<MyNS2::AmbiguousSwap>::value':
>    99 |         static_assert(!cuda::std::is_swappable<MyNS2::AmbiguousSwap>::value, "");
>       |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated when compiling for sm_60.
> ```

Oh it broke a lot more, that I am currently investigating. That test is absolutely fine, as it verified that we do not accept ambiguous swap. 

That would also apply to `std::swap`, so we must give any ADL found overload of swap precedence

**Comment by Artem-B** [comment]
Looks like CL is green again. Would you be able to update your backport branch, so I can test the current changes with v2.3.2?

**Comment by miscco** [comment]
> Looks like CL is green again. Would you be able to update your backport branch, so I can test the current changes with v2.3.2?

Done

**Comment by Artem-B** [comment]
All tests pass on my side. Thank you for backporting the fixes!

**Review by wmaxey — APPROVED** [review]
