### PR TITLE
Fix atomic performance regressions by avoiding use of memcpy with natively supported atomic types.

### LINKED ISSUE #1769: Fix 1B load/stores in atomic caused by refactoring

### PR DESCRIPTION
**Pull request by wmaxey**
## Description

closes #1769

Fixes codegen for scalar types when using atomic/atomic_ref.

## Checklist

- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

### CODE REVIEW

File: libcudacxx/codegen/codegen.cpp [hunk 1]
```diff
@@ -326,30 +334,52 @@ _LIBCUDACXX_BEGIN_NAMESPACE_STD
             }
             for (auto& cv : cv_qualifier)
             {
+              out << "template<class _Type, _CUDA_VSTD::__enable_if_t<sizeof(_Type)==" << sz / 8;
+              if (type.first == "f")
+              {
+                out << " && _CUDA_VSTD::is_floating_point<_Type>::value, int> = 0>\n";
```
Comment (miscco) [inline libcudacxx/codegen/codegen.cpp:340]: We should replace all the `is_meow<...>::value` with `_CCCL_TRAIT(is_meow, ...)` that way in c++14 and on we will use the cheap inline variable and not the struct

**Review by miscco — COMMENTED** [review]
I will let @griwes review this as he is much more into atomics then I am. 

I did not spot anything wrong though.

**Comment by wmaxey** [comment]
pre-commit.ci autofix

File: libcudacxx/codegen/codegen.cpp (hunk 1 above)
Comment (wmaxey) [reply libcudacxx/codegen/codegen.cpp]: Thanks for the fix on top of my 'fix'. Hah

File: libcudacxx/codegen/codegen.cpp [hunk 2]
```diff
@@ -326,30 +333,52 @@ _LIBCUDACXX_BEGIN_NAMESPACE_STD
...
+              else if (rmw.first == "fetch_max" || rmw.first == "fetch_min")
+              {
+                if (type.first == "u")
+                {
+                  out << " && _CCCL_TRAIT(is_integral, _Type) && _CCCL_TRAIT(is_unsigned, _Type), int> "
+                         "= 0>\n";
+                }
+                else if (type.first == "s")
+                {
+                  out << " && _CCCL_TRAIT(is_integral, _Type) && _CCCL_TRAIT(is_signed, _Type), int> = "
```
Comment (griwes) [inline libcudacxx/codegen/codegen.cpp:350]: These shouldn't need `is_integral`, no? Just `is_{,un}signed`?

File: libcudacxx/include/cuda/std/__atomic/functions/cuda_ptx_derived.h [hunk 3]
```diff
@@ -22,12 +22,78 @@
...
+  int __failure_memorder,
+  _Sco)
+{
+  using __proxy_t = _If<sizeof(_Tp) == 4, uint32_t, uint64_t>;
+  __proxy_t __old = 0;
+  __proxy_t __new = 0;
+  memcpy(&__old, __expected, sizeof(__proxy_t));
+  memcpy(&__new, &__desired, sizeof(__proxy_t));
+  bool __result = __atomic_compare_exchange_cuda(
+    reinterpret_cast<volatile __proxy_t*>(__ptr), &__old, __new, __weak, __success_memorder, __failure_memorder, _Sco{});
```
Comment (griwes) [inline libcudacxx/include/cuda/std/__atomic/functions/cuda_ptx_derived.h:52]: These casts are illegal.

I can see a way around it, though - have the underlying integer versions of these functions, and the PTX wrappers, take void pointers for the first arguments. Since it is used only in the inline PTX, it doesn't actually need to carry the type information with it, so that should be fine.

**Review by griwes — CHANGES_REQUESTED** [review]

File: libcudacxx/codegen/codegen.cpp (hunk 2 above)
Comment (wmaxey) [reply libcudacxx/codegen/codegen.cpp:350]: We need to differentiate from floating point types in this case. This code is unchanged. It was just moved from below.

File: libcudacxx/include/cuda/std/__atomic/functions/cuda_ptx_derived.h (hunk 3 above)
Comment (wmaxey) [reply libcudacxx/include/cuda/std/__atomic/functions/cuda_ptx_derived.h]: I believe this is now resolved.

**Review by griwes — APPROVED** [review]

**Comment by wmaxey** [comment]
pre-commit.ci autofix
