### PR TITLE
Check for windows platform rather than MSVC for `aligned_alloc`

### LINKED ISSUE #4370: [BUG]: If directive does not guard against std::aligned_alloc when compiled with Clang on Window
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Compile-time Error

### Component

libcu++

### Describe the bug

Windows SDK does not have an implementation for `std::aligned_alloc` (https://github.com/microsoft/STL/issues/2176). 

Thus in the file  `include/cuda/std/detail/libcxx/include/cstdlib`,  on Line 140 an `#if` directive is present to guard against it:

```
#  if _CCCL_STD_VER >= 2017 && !_CCCL_COMPILER(MSVC)
using ::aligned_alloc;
#  endif // _CCCL_STD_VER >= 2017 && !_CCCL_COMPILER(MSVC)

```
However, this does not take into account the case where we use the Clang compiler (instead of MSVC) on Windows. 

We have found a workaround:

```
#  if _CCCL_STD_VER >= 2017 && !_CCCL_OS(WINDOWS)
using ::aligned_alloc;
#  endif // _CCCL_STD_VER >= 2017 && !_CCCL_OS(WINDOWS)
```

Please consider this or another fix. Thank you!

### How to Reproduce

Make use of any other compiler on Windows besides MSVC, for building. We use the Clang17 compiler with WinSDK.

### Expected behavior

With the current library version we get the following compilation error:

Image

We would like that to go away.

### Reproduction link

_No response_

### Operating System

Windows 11 Enterprise

### nvidia-smi output

_No response_

### NVCC version

_No response_

### PR DESCRIPTION
**Pull request by miscco**
Fixes #4370

### CODE REVIEW

File: libcudacxx/include/cuda/std/__cstdlib/aligned_alloc.h [hunk 1]
```diff
@@ -41,7 +41,7 @@ _LIBCUDACXX_BEGIN_NAMESPACE_STD
 [[nodiscard]] _CCCL_HIDE_FROM_ABI _CCCL_HOST void*
 __aligned_alloc_host([[maybe_unused]] size_t __nbytes, [[maybe_unused]] size_t __align) noexcept
 {
-#  if _CCCL_COMPILER(MSVC)
+#  if _CCCL_OS(WINDOWS)
   _CCCL_ASSERT(false, "Use of aligned_alloc in host code is not supported with MSVC");
```
Comment (davebayer) [inline libcudacxx/include/cuda/std/__cstdlib/aligned_alloc.h:45]:
```suggestion
  _CCCL_ASSERT(false, "Use of aligned_alloc in host code is not supported on WIndows");
```

File: libcudacxx/include/cuda/std/__cstdlib/aligned_alloc.h [hunk 2]
```diff
@@ -41,8 +41,8 @@ _LIBCUDACXX_BEGIN_NAMESPACE_STD
 [[nodiscard]] _CCCL_HIDE_FROM_ABI _CCCL_HOST void*
 __aligned_alloc_host([[maybe_unused]] size_t __nbytes, [[maybe_unused]] size_t __align) noexcept
 {
-#  if _CCCL_COMPILER(MSVC)
-  _CCCL_ASSERT(false, "Use of aligned_alloc in host code is not supported with MSVC");
+#  if _CCCL_OS(WINDOWS)
+  _CCCL_ASSERT(false, "Use of aligned_alloc in host code is not supported on WIndows");
```
Comment (bernhardmgruber) [inline libcudacxx/include/cuda/std/__cstdlib/aligned_alloc.h:45]:
```suggestion
  _CCCL_ASSERT(false, "Use of aligned_alloc in host code is not supported on Windows");
```

**Review by bernhardmgruber — APPROVED** [review]
