### PR TITLE
[c.parallel]: migrate transform to use jit templates instead of string based implementations

### LINKED ISSUE #7387: [BUG] c.parallel: Stateful ops don't work with `transform` (and some other algorithms)
Stateful ops don't work with `transform` (and other algorithms that take the `kernels/operators.h` path as opposed to `jit_templates`).

I was able to vibe code a solution; I'll open a PR for feedback.

```c++
struct transform_stateful_counter_state_t
{
  int* d_counter;
};

C2H_TEST("Transform works with stateful unary operators", "[transform]")
{
  const std::size_t num_items = GENERATE(0, 42, take(4, random(1 << 12, 1 << 16)));
  pointer_t<int> counter(1);
  stateful_operation_t<transform_stateful_counter_state_t> op = make_operation(
    "op",
    R"(struct transform_stateful_counter_state_t { int* d_counter; };
extern "C" __device__ void op(void* state_ptr, void* x_ptr, void* out_ptr) {
  auto* state = static_cast<transform_stateful_counter_state_t*>(state_ptr);
  atomicAdd(state->d_counter, 1);
  int x = *static_cast<int*>(x_ptr);
  *static_cast<int*>(out_ptr) = x * 2;
})",
    transform_stateful_counter_state_t{counter.ptr});

  const std::vector<int> input = generate<int>(num_items);
  const std::vector<int> output(num_items, 0);
  pointer_t<int> input_ptr(input);
  pointer_t<int> output_ptr(output);

  std::optional<transform_build_cache_t> build_cache = std::nullopt;
  std::optional<std::string> test_key                = std::nullopt;

  unary_transform(input_ptr, output_ptr, num_items, op, build_cache, test_key);

  std::vector<int> expected(num_items, 0);
  std::transform(input.begin(), input.end(), expected.begin(), [](int x) {
    return x * 2;
  });

  if (num_items > 0)
  {
    REQUIRE(expected == std::vector<int>(output_ptr));
    REQUIRE(counter[0] == static_cast<int>(num_items));
  }
}

```

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cccl.c.parallel.test.transform is a Catch2 v3.8.1 host application.
Run with -? for options

-------------------------------------------------------------------------------
"Transform works with stateful unary operators"(0) - types_668 - 0
-------------------------------------------------------------------------------
/home/ashwin/workspace/cccl/c/parallel/test/test_transform.cpp:668
...............................................................................

/home/ashwin/workspace/cccl/c/parallel/test/test_util.h:712: FAILED:
  REQUIRE( cudaSuccess == cudaFree(ptr) )
with expansion:
  0 (no error) == 716 (misaligned address)

terminate called after throwing an instance of 'Catch::TestFailureException'
/home/ashwin/workspace/cccl/c/parallel/test/test_util.h:712: FAILED:
  {Unknown expression after the reported line}
due to a fatal error condition:
  SIGABRT - Abort (abnormal termination) signal

===============================================================================
test cases:  1 |  0 passed | 1 failed
assertions: 36 | 34 passed | 2 failed

```

### PR DESCRIPTION
**Pull request by NaderAlAwar**
## Description

closes #7387

Additionally, this PR makes changes to jit_templates to handle algorithms which could contain more than one type erased storage type. Prior to this, it was assumed that only one `storage_t` exists, but this change allows the caller to use a `tagged_arg` which contains a tag specifying the name of the storage type. This enables algorithms to define storage types with different sizes and alignments.

## Checklist

- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

### CODE REVIEW

File: c/parallel/src/jit_templates/traits.h [hunk 1]
```diff
@@ -27,16 +27,68 @@ template <typename Tpl>
...
 struct specialization
 {
   std::string type_name;
   std::string aux_code = "";
 };
 
-template <typename Tag,
-          typename Traits,
-          typename... Args,
-          typename = Traits::template type<void, parameter_mapping<Args>::archetype...>>
```
Comment (griwes) [inline c/parallel/src/jit_templates/traits.h:39]: I would like us to preserve the archetype part, either here or in the body of the function, so that if someone tries to pass in nonsensical arguments that are not accepted by the template in question, they still get an error here rather than at JIT time.

File: c/parallel/src/jit_templates/templates/operation.h [hunk 2]
```diff
@@ -292,6 +292,11 @@ __device__ {1} operator{2}(const {3} & lhs, const {3} & rhs)
   template <typename, typename... Args>
   static cuda::std::optional<specialization> special(cccl_op_t operation, cccl_type_info ret, Args... arguments)
   {
+    if (ret.type == cccl_type_enum::CCCL_STORAGE || ((arguments.type == cccl_type_enum::CCCL_STORAGE) || ...))
+    {
+      return cuda::std::nullopt;
+    }
```
Comment (griwes) [inline c/parallel/src/jit_templates/templates/operation.h]: This is a bit of a regression; originally, @gevtushenko asked to also lower to `cuda::std::foo` for storage types, after giving them an `operator foo`, and that's handled within the `if (entry->symbol)` branch below. Can you see if that can be preserved here?

File: c/parallel/src/jit_templates/templates/operation.h [hunk 3]
```diff
@@ -320,6 +325,15 @@ __device__ {1} operator{2}(const {3} & lhs, const {3} & rhs)
...
     return specialization{std::format(entry->name, cccl_type_enum_to_name(type_info_table[1]).c_str()), aux};
   }
+
+  template <typename Tag, typename RetStorageT, typename... ArgStorageTs>
+  static cuda::std::optional<specialization>
+  special(cccl_op_t operation,
+          tagged_arg<RetStorageT, cccl_type_info> ret,
+          tagged_arg<ArgStorageTs, cccl_type_info>... arguments)
+  {
+    return special<Tag>(operation, ret.value, arguments.value...);
```
Comment (griwes) [inline c/parallel/src/jit_templates/templates/operation.h]: If we preserve the behavior I mention above, the logic here should be reversed, i.e. `special` should accept anything, pass it through a `wrap` function that either returns the argument as is when it's tagged, or tags it with `storage_t` if it's not, and then the calls to `cccl_type_enum_to_name` above should use the tag for each argument, as the function above now has access to it.

File: c/parallel/src/jit_templates/traits.h (hunk 1 above)
Comment (NaderAlAwar) [reply c/parallel/src/jit_templates/traits.h:39]: Added it back

File: c/parallel/src/jit_templates/templates/operation.h (hunk 2 above)
Comment (NaderAlAwar) [reply c/parallel/src/jit_templates/templates/operation.h]: Reverted the change, although now this test https://github.com/NVIDIA/cccl/blob/ce3629efcbe10160af85a7d537578a60884f978a/c/parallel/test/test_transform.cpp#L351 is failing since it expects input and output types to be the same, which is no longer the case now that we introduced different input and output storage types, which won't work since the op type is set to `NEGATE`

Comment (NaderAlAwar) [reply c/parallel/src/jit_templates/templates/operation.h]: We discussed this offline:
* The well known operators path with storage types will currently not work because there is no way for the C API to tell whether two storage types are the same or not. This is an issue because operators like `negate` require the input and output types to be the same
* It might be possible to use the upper bits of the type enum as a storage type discriminator, but this is beyond the scope of this PR
* We will open an issue to enhance the C API to tell whether two storage types are the same

For now I will keep my original change which bails out if a well known operator is used with storage types
