### PR TITLE
This improves the detection logic for `__cccl_ptx_isa` for clang-cuda

### LINKED ISSUE #3633: [BUG]: Clang CUDA builds fail for sm90/sm90a with CTK 12.8
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Compile-time Error

### Component

libcu++

### Describe the bug

```
  Standard Error:
  --
  ptxas /tmp/ptx-sm_90-cb5cf6.s, line 155; error   : Feature 'cp.async.bulk with destination state space as .shared::cta' requires PTX ISA .version 8.6 or later
  ptxas fatal   : Ptx assembly aborted due to errors
```

### How to Reproduce

` .devcontainer/launch.sh -d -c 12.8 -H llvm18 -- "./ci/build_libcudacxx.sh" -std "20" -arch "90" -cuda "clang++"`

### Expected behavior

Build without failure.

### Reproduction link

_No response_

### Operating System

_No response_

### nvidia-smi output

_No response_

### NVCC version

_No response_

### PR DESCRIPTION
**Pull request by miscco**
We can actually check in the release branch of the respective release, whether clang-cuda marks a given PTX ISA as supported.

I went through all the relevant releases down to ptx 7.0 because we do select some code paths based on that

Fixes #3633

### CODE REVIEW

File: libcudacxx/include/cuda/std/__cccl/ptx_isa.h [hunk 1]
```diff
@@ -34,29 +34,59 @@
...
 #  define __cccl_ptx_isa 820ULL
 // PTX ISA 8.1 is available from CUDA 12.1, driver r530
-#elif _CCCL_CUDACC_AT_LEAST(12, 1)
+#elif _CCCL_CUDACC_AT_LEAST(12, 1) && !_CCCL_CUDA_COMPILER(CLANG, <, 17)
 #  define __cccl_ptx_isa 810ULL
 // PTX ISA 8.0 is available from CUDA 12.0, driver r525
-#elif _CCCL_CUDACC_AT_LEAST(12, 0)
+#elif _CCCL_CUDACC_AT_LEAST(12, 0) && !_CCCL_CUDA_COMPILER(CLANG, <, 17)
 #  define __cccl_ptx_isa 800ULL
+// PTX ISA 7.8 is available from CUDA 11.8, driver r520
```
Comment (ahendriksen) [inline libcudacxx/include/cuda/std/__cccl/ptx_isa.h:62]: Question: Why are the lines below added and not modified? Did we remove those lines in preparation for the next release?

**Review by ahendriksen — APPROVED** [review]
LGTM

File: libcudacxx/include/cuda/std/__cccl/ptx_isa.h (hunk 1 above)
Comment (miscco) [reply libcudacxx/include/cuda/std/__cccl/ptx_isa.h:62]: Those lines were removed when dropping support for CTK pre 12.0 but I found it sensible to have these in here because we do support down to clang-14 at least and it does not cost anything

Comment (bernhardmgruber) [reply libcudacxx/include/cuda/std/__cccl/ptx_isa.h:62]: We removed those lines with the nvcc 11.x support here: https://github.com/NVIDIA/cccl/pull/3596/files#diff-c1970f9174ca95aa30e79850d1fe200344dc0f26e6702c64564aca2e72f4ec0f

I think it's fine to re-add those lines.

**Review by bernhardmgruber — APPROVED** [review]
