### PR TITLE
thrust/mr: fix the case of reuising a block for a smaller alloc.

### LINKED ISSUE #585: Memory pool gets corrupted when oversized allocations are returned to pool out of order
When I perform oversized (i.e. > 1 MB) allocations and deallocations from a `thrust::mr::unsynchronized_pool_resource`, the linked list used by Thrust to keep track of the oversized allocations seems to get corrupted when I perform the allocations and deallocations in arbitrary order. For comparison, when the order of deallocations is the exact reverse of the order of allocations, everything seems to go well.

This piece of code leads to a segmentation fault:
```c++
#include <thrust/mr/pool.h>

#include <cstdlib>
#include <memory>
#include <string>

class HostPool
{
public:
  HostPool()
  {
    auto options = Pool::get_default_options();
    options.cache_oversized = true;
    _pool = std::make_unique<Pool>(options);
  }

  void * allocate(std::size_t mem_size)
  {
    return _pool->do_allocate(mem_size, THRUST_MR_DEFAULT_ALIGNMENT);
  }

  void deallocate(void *ptr, std::size_t size)
  {
    _pool->do_deallocate(ptr, size, THRUST_MR_DEFAULT_ALIGNMENT);
  }

private:
  class HostResource : public thrust::mr::memory_resource<>
  {
  public:
    void * do_allocate(std::size_t bytes, std::size_t alignment = THRUST_MR_DEFAULT_ALIGNMENT) override
    {
      return std::malloc(bytes);
    }

    void do_deallocate(void * p, std::size_t bytes,
                       std::size_t alignment = THRUST_MR_DEFAULT_ALIGNMENT) override
    {
      std::free(p);
    }
  };

  using Pool = thrust::mr::unsynchronized_pool_resource<HostResource>;

  std::unique_ptr<Pool> _pool;
};

int main()
{
  HostPool pool;

  auto ptr1 = pool.allocate(7320040);
  std::memset(ptr1, 0xff, 7320040);
  auto ptr2 = pool.allocate(14640080);
  std::memset(ptr2, 0xff, 14640080);
  pool.deallocate(ptr1, 7320040);
  pool.deallocate(ptr2, 14640080);
  auto ptr3 = pool.allocate(2465264);
  std::memset(ptr3, 0xff, 2465264);
  auto ptr4 = pool.allocate(2465264);
  std::memset(ptr4, 0xff, 2465264);
  pool.deallocate(ptr3, 2465264);
  pool.deallocate(ptr4, 2465264);
  auto ptr5 = pool.allocate(2465264);
  std::memset(ptr5, 0xff, 2465264);
  pool.deallocate(ptr5, 2465264);
  auto ptr6 = pool.allocate(2465264);
  std::memset(ptr6, 0xff, 2465264);
  auto ptr7 = pool.allocate(2465264);
  std::memset(ptr7, 0xff, 2465264);
  auto ptr8 = pool.allocate(2465264);
  std::memset(ptr8, 0xff, 2465264);
  pool.deallocate(ptr6, 2465264);
  auto ptr9 = pool.allocate(14791584);
  std::memset(ptr9, 0xff, 14791584);
  auto ptr10 = pool.allocate(4930528);
  std::memset(ptr10, 0xff, 4930528);
  pool.deallocate(ptr7, 2465264);
  pool.deallocate(ptr8, 2465264);
  pool.deallocate(ptr9, 14791584);
  pool.deallocate(ptr10, 4930528);
  auto ptr11 = pool.allocate(21960120);
  std::memset(ptr11, 0xff, 21960120);
  auto ptr12 = pool.allocate(2465264);
  std::memset(ptr12, 0xff, 2465264);
  auto ptr13 = pool.allocate(43920240);
  std::memset(ptr13, 0xff, 43920240);
  pool.deallocate(ptr11, 21960120);
  pool.deallocate(ptr12, 2465264);
  auto ptr14 = pool.allocate(2465264);
  std::memset(ptr14, 0xff, 2465264);
  pool.deallocate(ptr13, 43920240);
  pool.deallocate(ptr14, 2465264);
  auto ptr15 = pool.allocate(14640080);
  std::memset(ptr15, 0xff, 14640080);
  auto ptr16 = pool.allocate(4930528);
  std::memset(ptr16, 0xff, 4930528);
  pool.deallocate(ptr15, 14640080);
  pool.deallocate(ptr16, 4930528);
  auto ptr17 = pool.allocate(14640080);
  std::memset(ptr17, 0xff, 14640080);

  auto crash = pool.allocate(4930528);

  std::memset(crash, 0xff, 4930528);
  pool.deallocate(crash, 4930528);
  pool.deallocate(ptr17, 14640080);
  return 0;
}
```
All the allocations and deallocations here are in pairs and specify matching sizes, yet the last allocation leads to a crash. Debugging inside Thrust shows that [`m_cached_oversized`](https://github.com/NVIDIA/thrust/blob/1.16.0/thrust/mr/pool.h#L264) points to memory that looks like it has been overwritten by the `memset` calls in my sample.

I am observing this with Thrust 1.16.0, but since the memory pool implementation hasn't changed in years, I expect it also happens in Thrust 1.17.2 and 2.x. My original sample was obviously using device memory instead of `std::malloc`/`std::free`, but after I noticed where the bug is, I was able to switch to host memory to completely eliminate CUDA and NVCC from the reproducer.

### PR DESCRIPTION
**Pull request by griwes**
## Description

Previously, the pool happily returned a pointer to a larger oversized block than requested, without storing the information that the block is now smaller, which meant that on deallocation, it'd look for the descriptor of the block in the wrong place. This is now fixed by moving the descriptor to always be where deallocation can find it using the user-provided size, and by storing the original size to restore the descriptor to its rightful place when deallocating.

Also a drive-by fix for a bug where in certain cases the reallocated cached oversized block wasn't removed from the cached list. Whoops. Kinda surprised this hasn't exploded before.

Resolves #585 

## Checklist

- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

File: thrust/thrust/mr/pool.h [hunk 1]
```diff
@@ -305,23 +309,43 @@ class unsynchronized_pool_resource final
...
+
+                        if (bytes != desc.size) {
+                            desc.current_size = bytes;
+
+                            ptr = static_cast<oversized_block_descriptor_ptr>(
+                                static_cast<void_ptr>(ret + bytes));
+
+                            if (detail::pointer_traits<
+                                    oversized_block_descriptor_ptr>::
+                                    get(desc.prev)) {
```
Comment (miscco) [inline thrust/thrust/mr/pool.h:333]: suggestion: This would read much better if we added an alias:
```suggestion
                            using pointer_traits = detail::pointer_traits<oversized_block_descriptor_ptr>;
                            if (pointer_traits::get(desc.prev)) {
```

File: thrust/thrust/mr/pool.h [hunk 2]
```diff
@@ -305,23 +309,43 @@ class unsynchronized_pool_resource final
...
+                                thrust::raw_reference_cast(*desc.prev).next = ptr;
+                            } else {
+                                m_oversized = ptr;
+                            }
+
+                            if (detail::pointer_traits<
+                                    oversized_block_descriptor_ptr>::
+                                    get(desc.next)) {
```
Comment (miscco) [inline thrust/thrust/mr/pool.h:341]: And here we could reuse that alias
```suggestion
                            if (pointer_traits::get(desc.next)) {
```

File: thrust/thrust/mr/pool.h [hunk 3]
```diff
@@ -451,35 +476,47 @@ class unsynchronized_pool_resource final
...
                 desc.next_cached = m_cached_oversized;
-                *block = desc;
+
+                if (desc.size != n) {
+                    desc.current_size = desc.size;
+                    block = static_cast<oversized_block_descriptor_ptr>(
+                        static_cast<void_ptr>(static_cast<char_ptr>(p) +
+                                              desc.size));
+                    if (detail::pointer_traits<
+                            oversized_block_descriptor_ptr>::get(desc.prev)) {
```
Comment (miscco) [inline thrust/thrust/mr/pool.h:492]: Ditto
```suggestion
                    using pointer_traits = detail::pointer_traits<oversized_block_descriptor_ptr>;
                    if (pointer_traits::get(desc.prev)) {
```

File: thrust/thrust/mr/pool.h [hunk 4]
```diff
@@ -451,35 +476,47 @@ class unsynchronized_pool_resource final
...
+                        thrust::raw_reference_cast(*desc.prev).next = block;
+                    } else {
+                        m_oversized = block;
+                    }
+
+                    if (detail::pointer_traits<
+                            oversized_block_descriptor_ptr>::get(desc.next)) {
```
Comment (miscco) [inline thrust/thrust/mr/pool.h:499]:
```suggestion
                    if (pointer_traits::get(desc.next)) {
```

File: thrust/thrust/mr/pool.h [hunk 5]
```diff
@@ -451,35 +476,47 @@ class unsynchronized_pool_resource final
...
                 m_cached_oversized = block;
+                *block = desc;
 
                 return;
             }
 
-            if (!detail::pointer_traits<oversized_block_descriptor_ptr>::get(desc.prev))
-            {
-                assert(m_oversized == block);
+            if (detail::pointer_traits<oversized_block_descriptor_ptr>::get(
```
Comment (miscco) [inline thrust/thrust/mr/pool.h:510]: Maybe even pull the alias up so that we can reuse it here or make it a member of the class?

**Review by miscco — APPROVED** [review]
Looks good to me. 

Some suggestions regarding improved readability

File: thrust/testing/mr_pool.cu [hunk 6]
```diff
@@ -123,23 +123,26 @@ public:
 
     virtual tracked_pointer<void> do_allocate(std::size_t n, std::size_t alignment = THRUST_MR_DEFAULT_ALIGNMENT) override
     {
-        ASSERT_EQUAL(static_cast<bool>(id_to_allocate), true);
+        ASSERT_EQUAL(id_to_allocate || id_to_allocate == -1u, true);
```
[the remark this answers is not in the document]
Comment (griwes) [reply thrust/testing/mr_pool.cu:126]: I feel that this would be inconsistent without also changing the constants of `0`, and that just makes this file very messy IMO.
