### PR TITLE
Do not pass integral constants to ptx 

### LINKED ISSUE #2225: Inline asm constraint violation in cp_async_bulk_wait_group.h and fence.h
Clang complains about inline asm constraint violation: 
```
In file included from test/libcudacxx/cuda/ptx/ptx.cp.async.bulk.wait_group.compile.pass.cpp:14:
In file included from include/cuda/ptx:76:
include/cuda/__ptx/instructions/cp_async_bulk_wait_group.h:48:19: error: constraint 'n' expects an integer constant expression
   48 |     (asm volatile("cp.async.bulk.wait_group %0;"
      |                   ^
include/cuda/__ptx/instructions/cp_async_bulk_wait_group.h:71:19: error: constraint 'n' expects an integer constant expression
   71 |     (asm volatile("cp.async.bulk.wait_group.read %0;"
      |                   ^
2 errors generated when compiling for sm_90.
```

https://github.com/NVIDIA/cccl/blob/6ee3415a8d0eea82d0d6f9915aa249a6ceb13e24/libcudacxx/include/cuda/__ptx/instructions/cp_async_bulk_wait_group.h#L50

We're passing a function argument to an inline asm constraint that requires a constant.

Did we intend to use template argument `_N32` instead?

### PR DESCRIPTION
**Pull request by miscco**
Rather than passing the instance of integral_constant we should pass the value

Fixes #2225

### CODE REVIEW

File: libcudacxx/include/cuda/__ptx/instructions/cp_async_bulk_wait_group.h [hunk 1]
```diff
@@ -41,13 +41,13 @@ __device__ static inline void cp_async_bulk_wait_group(
...
 template <int _N32>
-_CCCL_DEVICE static inline void cp_async_bulk_wait_group(n32_t<_N32> __N)
+_CCCL_DEVICE static inline void cp_async_bulk_wait_group(n32_t<_N32> __n)
 {
   NV_IF_ELSE_TARGET(
     NV_PROVIDES_SM_90,
     (asm volatile("cp.async.bulk.wait_group %0;"
                   :
-                  : "n"(__N)
+                  : "n"(__n.value)
```
Comment (bernhardmgruber) [inline libcudacxx/include/cuda/__ptx/instructions/cp_async_bulk_wait_group.h:50]: Suggestion: How about using just the template parameter `_N32`? I am not certain `__n` is a constant expression here, and therefore some compilers complain that `__n.value` isn't either. I am also not sure whether that's required here.

Comment (miscco) [reply libcudacxx/include/cuda/__ptx/instructions/cp_async_bulk_wait_group.h:50]: `integral_constant.value` is a static constexpr variable, so `__n.value` is a constant expression even if it is accessed through a non-constant value

Comment (bernhardmgruber) [reply libcudacxx/include/cuda/__ptx/instructions/cp_async_bulk_wait_group.h:50]: I remember running into issues with this at some point, but I just checked on compiler explorer and could not reproduce it. All good then!

**Review by bernhardmgruber — APPROVED** [review]

File: libcudacxx/include/cuda/__ptx/instructions/cp_async_bulk_wait_group.h (hunk 1 above)
Comment (Artem-B) [reply libcudacxx/include/cuda/__ptx/instructions/cp_async_bulk_wait_group.h:50]: This popped up during one of the compilation tests I ran trying to import v2.5.0.  Does the error get triggered on one of cccl's tests w/ clang in your CI? I assume it should. It would give the definitive answer whether clang is OK with `__n.value`.

Comment (Artem-B) [reply libcudacxx/include/cuda/__ptx/instructions/cp_async_bulk_wait_group.h:50]: Looks like the tests do not build for sm_90a, so they would not catch stuff hidden behind `NV_HAS_FEATURE_SM_90a,`:
```
[41/1786] /usr/bin/sccache /usr/bin/clang++  -Dheadertest___ptx_instructions_tensormap_cp_fenceproxy_h_EXPORTS -I/home/coder/cccl/libcudacxx/include -O3 -DNDEBUG -std=gnu++20 --cuda-gpu-arch=sm_60 --cuda-gpu-arch=sm_70 --cuda-gpu-arch=sm_80 
```

Considering that there's nontrivial amount of interesting functionality that's specific to sm_90 and sm_90a, it may be useful to build/test for them, too.

Comment (miscco) [reply libcudacxx/include/cuda/__ptx/instructions/cp_async_bulk_wait_group.h:50]: That is really strange, considering we especially have a target for SM90a for that reason

Comment (miscco) [reply libcudacxx/include/cuda/__ptx/instructions/cp_async_bulk_wait_group.h:50]: Oh you know what, our SM90a tests only runs on nvcc with gcc https://github.com/NVIDIA/cccl/actions/runs/10368241031/job/28701520566

Comment (miscco) [reply libcudacxx/include/cuda/__ptx/instructions/cp_async_bulk_wait_group.h:50]: I added two CI runs for SM90 and SM90a, lets see what happens with that

**Comment by miscco** [comment]
@Artem-B So it seems SM_90a is not supported, which makes CI fail:
>      clang++: warning: CUDA version is newer than the latest partially supported version 12.1 [-Wunknown-cuda-version]
>      clang++: error: unsupported CUDA gpu architecture: sm_90a

I am seeing a lot of spurious clang erros, about initializing a `__shared__`variable, which is bogus, as we explicitly leave the variable uninitialized
```cpp
  __shared__ barrier bar; // <- error: initialization is not supported for __shared__ variables.
  if (threadIdx.x == 0)
  {
    init(&bar, blockDim.x);
  }
  __syncthreads();
```

**Comment by miscco** [comment]
Also looks like we need to revisit our PTX detection scheme for clang:
>  ptxas /tmp/ptx-sm_90-4a12ff.s, line 116; error   : Feature 'tensormap.cp_fenceproxy' requires PTX ISA .version 8.3 or later
>  ptxas /tmp/ptx-sm_90-4a12ff.s, line 140; error   : Feature 'tensormap.cp_fenceproxy' requires PTX ISA .version 8.3 or later
>  ptxas /tmp/ptx-sm_90-4a12ff.s, line 164; error   : Feature 'tensormap.cp_fenceproxy' requires PTX ISA .version 8.3 or later
>  ptxas /tmp/ptx-sm_90-4a12ff.s, line 188; error   : Feature 'tensormap.cp_fenceproxy' requires PTX ISA .version 8.3 or later

All of that is guarded by:
```cpp
#if __cccl_ptx_isa >= 830
```

Which in turn is defined as:
```cpp
#if (defined(__CUDACC_VER_MAJOR__) && (__CUDACC_VER_MAJOR__ > 12)) || (!defined(__CUDACC_VER_MAJOR__))
#  define __cccl_ptx_isa 830ULL
#elif (defined(__CUDACC_VER_MAJOR__) && (__CUDACC_VER_MAJOR__ >= 12 && __CUDACC_VER_MINOR__ >= 3)) \
  || (!defined(__CUDACC_VER_MAJOR__))
#  define __cccl_ptx_isa 830ULL
```

**Comment by miscco** [comment]
@Artem-B I am seeing some compiler crashes, could I drop them on you?

**Comment by miscco** [comment]
@Artem-B It seems something is wrong with the NV_TARGET implementation here:
https://github.com/NVIDIA/cccl/actions/runs/11102747639/job/30843396532?pr=2229

I dont really understand what is wrong there, so that it believes the variables are unused. 

Is that something that is worth investigating or can I just mark them as xfail for now?

File: libcudacxx/test/libcudacxx/cuda/memcpy_async_32.pass.cpp [hunk 2]
```diff
@@ -10,6 +10,9 @@
 
 // UNSUPPORTED: pre-sm-70
 
+// clang-cuda errors out with "fatal error: error in backend: Cannot cast between two non-generic address spaces"
```
Comment (Artem-B) [inline libcudacxx/test/libcudacxx/cuda/memcpy_async_32.pass.cpp:13]: BTW, these errors should be fixed in recent LLVM: https://github.com/llvm/llvm-project/pull/114325

File: libcudacxx/test/libcudacxx/cuda/barrier/cp_async_bulk_ptx_compiles.pass.cpp [hunk 3]
```diff
@@ -47,8 +47,8 @@ __global__ void test_bulk_tensor(CUtensorMap* map)
 __global__ void test_bulk(void* gmem)
 {
   __shared__ int smem;
-  __shared__ barrier bar;
-  cde::cp_async_bulk_global_to_shared(&smem, gmem, 1024, bar);
+  __shared__ barrier* bar;
+  cde::cp_async_bulk_global_to_shared(&smem, gmem, 1024, *bar);
```
Comment (Artem-B) [inline libcudacxx/test/libcudacxx/cuda/barrier/cp_async_bulk_ptx_compiles.pass.cpp:51]: This looks highly suspicious: https://godbolt.org/z/4Ma1Yq9M4

We end up using an unintialized value passed to `cp.async.bulk.shared::cluster.global.mbarrier::complete_tx::bytes` via `%r3`

```
.visible .entry _Z9test_bulkPv(
        .param .u64 _Z9test_bulkPv_param_0
)
{
        .reg .b32       %r<6>;
        .reg .b64       %rd<4>;
        .loc    1 6 0
        .shared .align 4 .u32 _ZZ9test_bulkPvE4smem;

        ld.param.u64    %rd3, [_Z9test_bulkPv_param_0];
        cvta.to.global.u64      %rd1, %rd3;
        mov.u32         %r1, _ZZ9test_bulkPvE4smem;
        mov.u32         %r5, 1024;
        cp.async.bulk.shared::cluster.global.mbarrier::complete_tx::bytes [%r1], [%rd1], %r5, [%r3]; // 1a. unicast
```

Comment (Artem-B) [reply libcudacxx/test/libcudacxx/cuda/barrier/cp_async_bulk_ptx_compiles.pass.cpp:51]: @miscco This is still an issue. We do need `bar` pointing to valid shared memory location. 

Using something like this appears to make the cp_async_bulk* tests work.
```
  alignas(128) __shared__ int smem_buffer[buf_len];
  __shared__ char barrier_data[sizeof(barrier)];
  barrier &bar = *reinterpret_cast<barrier*>(&barrier_data);
```

Comment (Artem-B) [reply libcudacxx/test/libcudacxx/cuda/barrier/cp_async_bulk_ptx_compiles.pass.cpp:51]: I guess this may be considered to be a new bug. I'll file the issue and send the patch tomorrow. LMK if this workaround is OK. I may still need to look at why clang complains about non-trivial initializer for `barrier`.

Comment (miscco) [reply libcudacxx/test/libcudacxx/cuda/barrier/cp_async_bulk_ptx_compiles.pass.cpp:51]: I believe this is an old version, on main it lreads:
```
  __shared__ barrier* bar;
  if (threadIdx.x == 0)
  {
    init(bar, blockDim.x);
  }

  cde::cp_async_bulk_global_to_shared(&smem, gmem, 1024, *bar);
```

Comment (Artem-B) [reply libcudacxx/test/libcudacxx/cuda/barrier/cp_async_bulk_ptx_compiles.pass.cpp:51]: The bar is still an uninitialized pointer and it's expected to be pointing to the valid data to initialized, and then used.
E.g. https://github.com/NVIDIA/cccl/blob/a92db6b1915d946b48a5e48013d5ca7fc898a67d/libcudacxx/include/cuda/__barrier/barrier_block_scope.h#L107

In the original comment I've quoted PTX the current code produces and it's clearly wrong. Re're passing `[%r3]` as the last `mbar` argument, but `r3` is not set to anything.

Comment (miscco) [reply libcudacxx/test/libcudacxx/cuda/barrier/cp_async_bulk_ptx_compiles.pass.cpp:51]: Oh we are missing the sync I believe, because `init(bar, blockDim.x)` does initialize it but we need to ensure that we wait for that

Comment (miscco) [reply libcudacxx/test/libcudacxx/cuda/barrier/cp_async_bulk_ptx_compiles.pass.cpp:51]: opened #3061

Comment (Artem-B) [reply libcudacxx/test/libcudacxx/cuda/barrier/cp_async_bulk_ptx_compiles.pass.cpp:51]: > init(bar, blockDim.x) does initialize it

I'm confused (or missing something). 
`bar` is a pointer, pointing who knows where, right? If we pass an invalid pointer to init, what exactly does `init` initialize then? AFAICT init() assumes that `bar` points to valid storage in shared memory.

In the original code `bar` was a variable and that looks like what the barrier APIs expect:
https://github.com/NVIDIA/cccl/blob/baee3f502d4fd5febc7f602428592b2bec5d2d3b/libcudacxx/test/libcudacxx/cuda/barrier/cp_async_bulk_tensor.pass.cpp#L71-L75

Comment (miscco) [reply libcudacxx/test/libcudacxx/cuda/barrier/cp_async_bulk_ptx_compiles.pass.cpp:51]: Sorry, I somehow totally misread what this thread was about and mentally filed it as fixed

Comment (Artem-B) [reply libcudacxx/test/libcudacxx/cuda/barrier/cp_async_bulk_ptx_compiles.pass.cpp:51]: Happens. I should've filed a separate issue rather than leave a comment on an already closed pull request... and then forget about it, too, because I've fixed it locally. I'll do better next time.
