### PR TITLE
Fix MSVC version detection

### LINKED ISSUE #7291: [INFRA]: Update Thrust's FindTBB for MSVC 2026
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Overview

The legacy TBB module we provide has hardcoded checks for msvc versions and do not recognize 2026.

### Details

We should probably just remove those checks as MSVC is a lot more stable than it used to be, and the older versions that we WAR are likely unsupported by CCCL. Investigate and either update or drop the checks.

NVBug 5781581.

### PR DESCRIPTION
**Pull request by miscco**
VS 2022 went further than 1939, so we need to account for that. 

VS2026 starts at 1950

### CODE REVIEW

**Comment by bernhardmgruber** [comment]
This addresses #7291, right?

**Comment by miscco** [comment]
yeah I just saw the nvbug

File: libcudacxx/include/cuda/std/__cccl/compiler.h [hunk 1]
```diff
@@ -90,10 +91,14 @@
...
-#  if _CCCL_COMPILER(MSVC, >=, 19, 30) && _CCCL_COMPILER(MSVC, <, 19, 40)
+#  if _CCCL_COMPILER(MSVC, >=, 19, 30) && _CCCL_COMPILER(MSVC, <, 19, 50)
 #    undef _CCCL_COMPILER_MSVC2022
 #    define _CCCL_COMPILER_MSVC2022() _CCCL_COMPILER_MSVC()
-#  endif // _CCCL_COMPILER(MSVC, >=, 19, 30) && _CCCL_COMPILER(MSVC, <, 19, 40)
+#  endif // _CCCL_COMPILER(MSVC, >=, 19, 30) && _CCCL_COMPILER(MSVC, <, 19, 50)
+#  if _CCCL_COMPILER(MSVC, >=, 19, 50)
+#    undef _CCCL_COMPILER_MSVC2026
+#    define _CCCL_COMPILER_MSVC2026() _CCCL_COMPILER_MSVC()
+#  endif // _CCCL_COMPILER(MSVC, >=, 19, 45)
```
Comment (davebayer) [inline libcudacxx/include/cuda/std/__cccl/compiler.h:102]: Hm, these macros are unused anyway, do we even need them?

File: lib/cmake/thrust/FindTBB.cmake [hunk 2]
```diff
@@ -254,12 +254,15 @@ if (WIN32 AND MSVC)
     set(COMPILER_PREFIX "vc11")
   elseif (MSVC_VERSION EQUAL 1800)
     set(COMPILER_PREFIX "vc12")
-  elseif (MSVC_VERSION GREATER_EQUAL 1900 AND MSVC_VERSION LESS_EQUAL 1939)
+  elseif (MSVC_VERSION GREATER_EQUAL 1900)
     # 1900-1925 actually spans three Visual Studio versions:
```
Comment (davebayer) [inline lib/cmake/thrust/FindTBB.cmake]:
```suggestion
    # 1900-1950 actually spans several Visual Studio versions:
```

File: libcudacxx/include/cuda/std/__cccl/compiler.h
Comment (davebayer) [inline libcudacxx/include/cuda/std/__cccl/compiler.h:62]:
```suggestion
#define _CCCL_COMPILER_MSVC2022() _CCCL_VERSION_INVALID()
#define _CCCL_COMPILER_MSVC2026() _CCCL_VERSION_INVALID()
```

**Review by davebayer — CHANGES_REQUESTED** [review]

File: libcudacxx/include/cuda/std/__cccl/compiler.h (hunk 1 above)
Comment (miscco) [reply libcudacxx/include/cuda/std/__cccl/compiler.h]: Sometimes they come in handy

File: lib/cmake/thrust/FindTBB.cmake [hunk 3]
```diff
@@ -254,12 +254,15 @@ if (WIN32 AND MSVC)
...
+  elseif (MSVC_VERSION GREATER_EQUAL 1900)
+    # 1900-1950 actually spans several Visual Studio versions:
     # 1900      = VS 14.0 (v140 toolset) a.k.a. MSVC 2015
     # 1910-1919 = VS 15.0 (v141 toolset) a.k.a. MSVC 2017
     # 1920-1929 = VS 16.0 (v142 toolset) a.k.a. MSVC 2019
-    # 1930-1939 = VS 17.0 (v143 toolset) a.k.a. MSVC 2022
+    # 1930-1944 = VS 17.0 (v143 toolset) a.k.a. MSVC 2022
+    # 1944 is the last version shipped in VS2022 after that the _MSC_VER is not bundled with the VS version anymore
+    # AFAIK it is still the same toolset even if the compiler is marked as 14.50
+    # 1950      = VS 18.0 (v144 toolset) a.k.a. MSVC 2026
```
Comment (davebayer) [inline lib/cmake/thrust/FindTBB.cmake:265]: From what I see in my computer it's v145 :D

**Review by davebayer — APPROVED** [review]

**Review by bernhardmgruber — APPROVED** [review]

**Review by davebayer — APPROVED** [review]
