### PR TITLE
change `cudax::uninitialized_buffer` to own its memory resource with `cudax::any_resource`

### LINKED ISSUE #2292: [BUG]: `cudax::uninitialized_buffer` should own its memory resource
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Something else

### Component

libcu++

### Describe the bug

`cuda::experimental::uninitialized_buffer` requires a memory resource from which it allocates the buffer. Right now, the user is required to construct an `uninitialized_buffer` object with a reference to a memory resource that they are responsible for keeping alive. If they fail to do that, the `uninitialized_buffer` will be left with a dangling reference, leading to crashes or worse.

### How to Reproduce

n/a

### Expected behavior

`uninitialized_buffer` should own the resource from which it is constructed. If the user wants the current by-ref semantics, they can construct an `uninitialized_buffer` with a `resource_ref`.

### Reproduction link

_No response_

### Operating System

_No response_

### nvidia-smi output

_No response_

### NVCC version

_No response_

### PR DESCRIPTION
**Pull request by ericniebler**
## Description

This PR addresses issue #2292 by changing `uninitialized_buffer` to store its memory resource in an `any_resource` instead of merely referring to a memory resource with `resource_ref`.

_**NOTE:** I will rebase this PR when #2266 lands._ See [7e33a5507726c8d21b7c5dd883dd68b2978b2704] for the changes in this PR.

closes #2292 

Change member `uninitialized_buffer::__mr_` from `resource_ref` to `any_resource`. Be sure to `std::move` `__mr_` when moving the owning `uninitialized_buffer`.

## Checklist

- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

File: cudax/include/cuda/experimental/__container/uninitialized_buffer.h [hunk 1]
```diff
@@ -51,20 +53,14 @@ namespace cuda::experimental
...
 //! @endrst
-//! @tparam _T the type to be stored in the buffer
+//! @tparam _Tp the type to be stored in the buffer
 //! @tparam _Properties... The properties the allocated memory satisfies
 template <class _Tp, class... _Properties>
 class uninitialized_buffer
 {
 private:
-  _CUDA_VMR::resource_ref<_Properties...> __mr_;
+  mr::any_resource<_Properties...> __mr_;
```
Comment (miscco) [inline cudax/include/cuda/experimental/__container/uninitialized_buffer.h:63]: Suggestion: This could potentially lead to name clashes, we should use fully qualified names
```suggestion
  ::cuda::experimental::mr::any_resource<_Properties...> __mr_;
```

File: cudax/include/cuda/experimental/__container/uninitialized_buffer.h [hunk 2]
```diff
@@ -97,8 +93,8 @@ class uninitialized_buffer
   //! @note Depending on the alignment requirements of `T` the size of the underlying allocation might be larger
   //! than `count * sizeof(T)`.
   //! @note Only allocates memory when \p __count > 0
-  uninitialized_buffer(_CUDA_VMR::resource_ref<_Properties...> __mr, const size_t __count)
-      : __mr_(__mr)
+  uninitialized_buffer(mr::any_resource<_Properties...> __mr, const size_t __count)
```
Comment (miscco) [inline cudax/include/cuda/experimental/__container/uninitialized_buffer.h:96]:
```suggestion
  uninitialized_buffer(::cuda::experimental::mr::any_resource<_Properties...> __mr, const size_t __count)
```

File: cudax/include/cuda/experimental/__container/uninitialized_buffer.h [hunk 3]
```diff
@@ -174,10 +170,9 @@ class uninitialized_buffer
   }
 
   //! @rst
-  //! Returns the :ref:`resource_ref <libcudacxx-extended-api-memory-resources-resource-ref>` used to allocate
-  //! the buffer
+  //! Returns a copy of the `any_resource` used to allocate the buffer
   //! @endrst
-  _CCCL_NODISCARD _CCCL_HOST_DEVICE _CUDA_VMR::resource_ref<_Properties...> resource() const noexcept
+  _CCCL_NODISCARD _CCCL_HOST_DEVICE mr::any_resource<_Properties...> resource() const noexcept
```
Comment (miscco) [inline cudax/include/cuda/experimental/__container/uninitialized_buffer.h:175]:
```suggestion
  _CCCL_NODISCARD _CCCL_HOST_DEVICE ::cuda::experimental::mr::any_resource<_Properties...> resource() const noexcept
```

**Review by miscco — APPROVED** [review]

File: cudax/include/cuda/experimental/__container/uninitialized_buffer.h [hunk 4]
```diff
@@ -174,19 +171,20 @@ class uninitialized_buffer
   }
 
   //! @rst
-  //! Returns the :ref:`resource_ref <libcudacxx-extended-api-memory-resources-resource-ref>` used to allocate
-  //! the buffer
+  //! Returns a :ref:`resource_ref <libcudacxx-extended-api-memory-resources-resource-ref>` to the resource used to
+  //! allocate the buffer
   //! @endrst
+  _CCCL_EXEC_CHECK_DISABLE
   _CCCL_NODISCARD _CCCL_HOST_DEVICE _CUDA_VMR::resource_ref<_Properties...> resource() const noexcept
```
Comment (miscco) [inline cudax/include/cuda/experimental/__container/uninitialized_buffer.h:178]: @ericniebler I kept this as a resource_ref
